barffood/Controllers/NovoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using barffood.Models;
using Rotativa;

namespace barffood.Controllers
{
    public class NovoController : Controller
    {
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {
                    Food este = db.Foods.Find(id ?? 0);
                    if (este != null)
                    {
                        return View(este);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Novo", new { msg = "Id não existe" });
                    }
                }
            }
            catch (Exception erro)
            {

                return RedirectToAction("Index", "Novo", new { msg = erro.Message });
            }
        }

        [HttpPost]
        public ActionResult Edit(Food editado, HttpPostedFileBase fich)
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {
                    Food este = db.Foods.Find(editado.idfood);
                    if (este != null)
                    {
                        este.nome = editado.nome;
                        este.url = editado.url;
                        este.data_validade = editado.data_validade;
                        if (fich != null && fich.ContentLength > 0 && fich.ContentType.Contains("image"))
                        {

                            string caminho = "~/fotos/" + este.idfood.ToString() + System.IO.Path.GetExtension(fich.FileName);
                            if (System.IO.File.Exists(Server.MapPath(caminho))) System.IO.File.Delete(Server.MapPath(caminho));
                            este.foto = caminho;
                            fich.SaveAs(Server.MapPath(caminho));

                        }
                        db.SaveChanges();
                        return RedirectToAction("Index", "Novo", new { msg = "Ok Registo editado com sucesso" });
                    }
                    else
                    {
                        return RedirectToAction("Index", "Novo", new { msg = "Id não existe" });

                    }

                }
            }
            catch (Exception erro)
            {

                return RedirectToAction("Index", "Novo", new { msg = erro.Message });
            }
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {
                    Food este = db.Foods.Find(id ?? 0);
                    if (este != null)
                    {
                        return View(este);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Novo", new { msg = "Cliente não existe" });
                    }
                }
            }
            catch (Exception erro)
            {

                return RedirectToAction("Index", "Novo", new { msg = erro.Message });
            }
        }


        [Authorize(Roles = "Admin")]
        public ActionResult DeleteFood(int? id)
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {
                    Food este = db.Foods.Find(id ?? 0);
                    if (este != null)
                    {
                        db.Foods.Remove(este);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Novo", new { msg = "Apagado com sucesso" });
                    }
                    else
                    {
                        return RedirectToAction("Index", "Novo", new { msg = "Del: id não existe" });
                    }
                }
            }
            catch (Exception erro)
            {

                return RedirectToAction("Index", "Novo", new { msg = erro.Message });
            }

        }
        [Authorize(Roles = "Admin")]
        public ActionResult AddFood()
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {
                    List<animal> animals = db.animals.ToList();
                    ViewBag.animals = new SelectList(animals, "idanimal", "idanimal");
                    List<Race> race = db.Races.ToList();
                    ViewBag.races = new SelectList(race, "idrace", "idrace");
                    Food food = new Food();
                    return View(food);
                }

            }
            catch (Exception erro)
            {

                throw;
            }
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddFood(Food novo, HttpPostedFileBase fich)
        {
            try
            {
                using (barffoodEntities2 db = new barffoodEntities2())
                {

                    db.Foods.Add(novo);
                    db.SaveChanges();
                    if (fich.ContentLength > 0 && fich.ContentType.Contains("image"))
                    {
                        string caminho = "~/fotos/" + novo.idfood.ToString() + System.IO.Path.GetExtension(fich.FileName);
                        novo.foto = caminho;
                        fich.SaveAs(Server.MapPath(caminho));
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index", "Novo", new { msg = "Registo inserido com sucesso" });
                }
            }
            catch (Exception erro)
            {

                return RedirectToAction("Index", "Novo", new { msg = erro.Message });
            }

        }

        // GET: Novo
        public ActionResult Index()
        {

            using (barffoodEntities2 db = new barffoodEntities2())
            {
                List<Food> comida = db.Foods.ToList();

                return View(comida);
            }

        }
        public ActionResult Contact()
        {
            return View();
        }
        //Convert Index Page as PDF
        public ActionResult PrintViewToPdf()
        {
            var report = new ActionAsPdf("Index");
            return report;
        }

        //Convert partial Page as PDF
        public ActionResult PrintPartialViewToPdf(int id)
        {
            using (barffoodEntities2 db = new barffoodEntities2())
            {
                Food employee = db.Foods.FirstOrDefault(e => e.idfood == id);
                var report = new PartialViewAsPdf("~/Views/Novo/Details.cshtml", employee);
                return report;
            }
        }
        
    }
}

barffood/Controllers/pdfconvertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using barffood.Models;
namespace barffood.Controllers
{
    public class pdfconvertController : Controller
    {

        // GET: Employee
        // Print the List of Employee Details
        public ActionResult Index()
        {
            using (barffoodEntities2 db = new barffoodEntities2())
            {
                var employeeList = db.Foods.ToList();
                return View(employeeList);
            }
        }

    
    }
}

barffood/Views/Novo/AddFood.cshtml
@model barffood.Models.Food

@{
    ViewBag.Title = "AddFood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddFood</h2>

@using (Html.BeginForm("AddFood","Novo",FormMethod.Post, new { id = "frm", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Food</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.animal, "idanimal", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idanimal", ViewBag.animals as SelectList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.animal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Race, "idrace", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idrace", ViewBag.races as SelectList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.data_validade, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.data_validade, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.data_validade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input type="file" class="form-control" name="fich" id="fich" onchange="loadFile(event);" />
            <img id="output" alt="" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



<script>
    $(function () {

    });
    var loadFile = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('output');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    };

</script>

barffood/Views/Novo/DeleteFood.cshtml
@model barffood.Models.Food

@{
    ViewBag.Title = "DeleteFood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteFood</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Food</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_validade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_validade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time_remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time_remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.animal.idanimal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.animal.idanimal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race.idrace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race.idrace)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

barffood/Views/Novo/Details.cshtml
@model barffood.Models.Food

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Food</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_validade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_validade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time_remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time_remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idfood }) |
    @Html.ActionLink("Back to List", "Index")
</p>

barffood/Views/Novo/Edit.cshtml
@model barffood.Models.Food

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Food</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idfood)



    <div class="form-group">
        @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.data_validade, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.data_validade, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.data_validade, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="fich" id="fich" class="form-control" onchange="loadFile(event);" />
            @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            <br />
            <img id="output" width="200" alt="" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
        $(function () {

        });

        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('output');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);

        };
</script>

barffood/Views/Novo/Index.cshtml
@model IEnumerable<barffood.Models.Food>
@using System.IO;
@using System.Text;
@using System.Data;
@using iTextSharp.text;
@using iTextSharp.text.pdf;
@using iTextSharp.text.html.simpleparser;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@if (User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Create New", "AddFood", "Novo")
    @Html.ActionLink("Convert View To PDF", "PrintViewToPdf","pdfconvert")
</p>
}

<div id="dvTable">
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.data_validade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time_remain)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th>
            Animal
        </th>
        <th>
            Raça
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data_validade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time_remain)
            </td>
            <td>
                @{
                    if (String.IsNullOrEmpty(item.foto))
                    {

                        <img width="80" src="@Url.Content("~/fotos/nofoto.png")" alt="erro" />

                    }
                    else
                    {

                        if (String.IsNullOrEmpty(item.url))
                        {
                            <img width="80" src="@Url.Content(item.foto)" alt="erro" />
                        }
                        else
                        {


                            <asp:LinkButton ID="ad_main_form" runat="server" OnClick="ad_button_Click"
                    OnClientClick="Navigate('@Html.DisplayFor(modelItem => item.url)')" CausesValidation="False">
                                <img width="80" src="@Url.Content(item.foto)" alt="erro" />
                            </asp:LinkButton>





                        }
                    }

                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idanimal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idrace)
            </td>
            <td>
                <a href="@Html.DisplayFor(modelItem => item.url)" target="_blank">@Html.DisplayFor(modelItem => item.url)</a>
            </td>
            @if (User.IsInRole("Admin"))
            {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idfood }) |
                @Html.ActionLink("Details", "Details", new { id = item.idfood }) |
                @Html.ActionLink("Print Details View To PDF", "PrintPartialViewToPdf", new { id = item.idfood }) |
                @Html.ActionLink("Delete", "DeleteFood", new { id = item.idfood })
            </td>
            }
        </tr>
    }

</table>
</div>
<input type="hidden" id="hfTableHTML" name="Table_HTML" />
<hr />
<button Onclick="Export()" >Submit</button>
@* <asp:Button Text="Export" runat="server" OnClick="Export" OnClientClick="SetHTML()" /> *@